// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: code/error.proto

package learn_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// example: 101010
// 1: service number, 01: model number, 010 error number
type Code int32

const (
	Code_UNSPECIFIED    Code = 0
	Code_INVALID_PARAMS Code = 101010
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:      "UNSPECIFIED",
		101010: "INVALID_PARAMS",
	}
	Code_value = map[string]int32{
		"UNSPECIFIED":    0,
		"INVALID_PARAMS": 101010,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_code_error_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_code_error_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_code_error_proto_rawDescGZIP(), []int{0}
}

var File_code_error_proto protoreflect.FileDescriptor

var file_code_error_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2a, 0x2d, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50,
	0x41, 0x52, 0x41, 0x4d, 0x53, 0x10, 0x92, 0x95, 0x06, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x6f, 0x63, 0x62, 0x61, 0x6e, 0x67,
	0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x2d, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_code_error_proto_rawDescOnce sync.Once
	file_code_error_proto_rawDescData = file_code_error_proto_rawDesc
)

func file_code_error_proto_rawDescGZIP() []byte {
	file_code_error_proto_rawDescOnce.Do(func() {
		file_code_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_code_error_proto_rawDescData)
	})
	return file_code_error_proto_rawDescData
}

var file_code_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code_error_proto_goTypes = []interface{}{
	(Code)(0), // 0: errors.Code
}
var file_code_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_error_proto_init() }
func file_code_error_proto_init() {
	if File_code_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_error_proto_goTypes,
		DependencyIndexes: file_code_error_proto_depIdxs,
		EnumInfos:         file_code_error_proto_enumTypes,
	}.Build()
	File_code_error_proto = out.File
	file_code_error_proto_rawDesc = nil
	file_code_error_proto_goTypes = nil
	file_code_error_proto_depIdxs = nil
}
